name: Reusable workflow example

on:
  workflow_call:
    secrets:
      JF_ENV_1:
        required: true

jobs:
  setupJFrog:
    name: setup jfrog
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repository
        uses: actions/checkout@v3

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_ENV_1: ${{ secrets.JF_ENV_1 }}

      - name: Setup JF mvn-config
        run: jf mvn-config  # uses JF_ENV_! to setup mvn config
